version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly" # 改为月度更新，减少频率
    open-pull-requests-limit: 3 # 限制同时打开的 PR 数量
    groups:
      # 将依赖分组，一次只产生一个 PR
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # 改为月度更新
    open-pull-requests-limit: 2
    groups:
      # 所有 GitHub Actions 更新合并为一个 PR
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
