import type { TagGraphSnapshot } from '@/types/tag-graph'

export const demoTagGraphSnapshot: TagGraphSnapshot = {
  id: 'demo-tag-universe-2025',
  layout: 'radial',
  version: '2025.09.23',
  generatedAt: new Date('2025-09-20T10:00:00.000Z').toISOString(),
  stats: {
    totalTags: 18,
    totalEdges: 24,
    maxFrequency: 128,
  },
  nodes: [
    {
      id: 'tag-neon',
      name: '霓虹',
      color: '#9B6BFF',
      radius: 72,
      frequency: 128,
      group: '夜幕叙事',
      role: 'primary',
      relatedCount: 8,
      featuredPhoto: {
        id: 'photo-neon-glow',
        src: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=640&q=80',
        alt: '霓虹灯下的模特',
      },
    },
    {
      id: 'tag-rain',
      name: '雨幕',
      color: '#6EA3FF',
      radius: 64,
      frequency: 96,
      group: '夜幕叙事',
      role: 'secondary',
      relatedCount: 6,
      featuredPhoto: {
        id: 'photo-rain-silhouette',
        src: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=640&q=80',
      },
    },
    {
      id: 'tag-mirror',
      name: '镜面',
      color: '#4AC4FF',
      radius: 56,
      frequency: 84,
      group: '夜幕叙事',
      role: 'secondary',
      relatedCount: 5,
    },
    {
      id: 'tag-golden-hour',
      name: '晨光',
      color: '#FFAF7A',
      radius: 68,
      frequency: 110,
      group: '自然光感',
      role: 'primary',
      relatedCount: 7,
      featuredPhoto: {
        id: 'photo-golden-beam',
        src: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=640&q=80',
      },
    },
    {
      id: 'tag-floral',
      name: '花序',
      color: '#FFE8C2',
      radius: 60,
      frequency: 88,
      group: '自然光感',
      role: 'secondary',
      relatedCount: 6,
    },
    {
      id: 'tag-gold',
      name: '金箔',
      color: '#FFD57A',
      radius: 52,
      frequency: 72,
      group: '自然光感',
      role: 'supporting',
      relatedCount: 4,
    },
    {
      id: 'tag-cinemagic',
      name: '电影光',
      color: '#FF6B6B',
      radius: 58,
      frequency: 80,
      group: '动态叙事',
      role: 'primary',
      relatedCount: 5,
    },
    {
      id: 'tag-motion',
      name: '慢门',
      color: '#FF928B',
      radius: 50,
      frequency: 68,
      group: '动态叙事',
      role: 'secondary',
      relatedCount: 4,
    },
    {
      id: 'tag-sound',
      name: '声音轨迹',
      color: '#C77DFF',
      radius: 48,
      frequency: 64,
      group: '动态叙事',
      role: 'supporting',
      relatedCount: 4,
    },
    {
      id: 'tag-portrait',
      name: '人像',
      color: '#F8D7FF',
      radius: 46,
      frequency: 60,
      group: '人物情绪',
      role: 'primary',
      relatedCount: 4,
    },
    {
      id: 'tag-expression',
      name: '情绪',
      color: '#F6A6FF',
      radius: 44,
      frequency: 56,
      group: '人物情绪',
      role: 'secondary',
      relatedCount: 3,
    },
    {
      id: 'tag-archive',
      name: '档案',
      color: '#8DEAFF',
      radius: 40,
      frequency: 48,
      group: '策展主题',
      role: 'secondary',
      relatedCount: 3,
    },
    {
      id: 'tag-workshop',
      name: '工作坊',
      color: '#5CE1E6',
      radius: 36,
      frequency: 40,
      group: '策展主题',
      role: 'supporting',
      relatedCount: 2,
    },
    {
      id: 'tag-lookbook',
      name: '造型集',
      color: '#FFB3C6',
      radius: 42,
      frequency: 52,
      group: '策展主题',
      role: 'secondary',
      relatedCount: 3,
    },
    {
      id: 'tag-sculpt',
      name: '造型雕塑',
      color: '#9B9EFF',
      radius: 38,
      frequency: 44,
      group: '实验装置',
      role: 'supporting',
      relatedCount: 2,
    },
    {
      id: 'tag-light-loop',
      name: '光环',
      color: '#78E3FD',
      radius: 34,
      frequency: 38,
      group: '实验装置',
      role: 'supporting',
      relatedCount: 2,
    },
    {
      id: 'tag-texture',
      name: '肌理',
      color: '#A6E3E9',
      radius: 36,
      frequency: 42,
      group: '实验装置',
      role: 'supporting',
      relatedCount: 2,
    },
    {
      id: 'tag-archive-night',
      name: '夜档案',
      color: '#7C83FD',
      radius: 40,
      frequency: 48,
      group: '策展主题',
      role: 'supporting',
      relatedCount: 3,
    },
  ],
  edges: [
    { id: 'edge-neon-rain', source: 'tag-neon', target: 'tag-rain', weight: 0.9 },
    { id: 'edge-neon-mirror', source: 'tag-neon', target: 'tag-mirror', weight: 0.8 },
    { id: 'edge-rain-mirror', source: 'tag-rain', target: 'tag-mirror', weight: 0.65 },
    { id: 'edge-neon-cinemagic', source: 'tag-neon', target: 'tag-cinemagic', weight: 0.6 },
    { id: 'edge-cinemagic-motion', source: 'tag-cinemagic', target: 'tag-motion', weight: 0.7 },
    { id: 'edge-motion-sound', source: 'tag-motion', target: 'tag-sound', weight: 0.55 },
    { id: 'edge-golden-floral', source: 'tag-golden-hour', target: 'tag-floral', weight: 0.82 },
    { id: 'edge-golden-gold', source: 'tag-golden-hour', target: 'tag-gold', weight: 0.7 },
    { id: 'edge-floral-gold', source: 'tag-floral', target: 'tag-gold', weight: 0.62 },
    { id: 'edge-golden-portrait', source: 'tag-golden-hour', target: 'tag-portrait', weight: 0.58 },
    { id: 'edge-portrait-expression', source: 'tag-portrait', target: 'tag-expression', weight: 0.65 },
    { id: 'edge-cinemagic-portrait', source: 'tag-cinemagic', target: 'tag-portrait', weight: 0.45 },
    { id: 'edge-archive-lookbook', source: 'tag-archive', target: 'tag-lookbook', weight: 0.52 },
    { id: 'edge-lookbook-workshop', source: 'tag-lookbook', target: 'tag-workshop', weight: 0.44 },
    { id: 'edge-archive-night', source: 'tag-archive', target: 'tag-archive-night', weight: 0.48 },
    { id: 'edge-lookbook-neon', source: 'tag-lookbook', target: 'tag-neon', weight: 0.35 },
    { id: 'edge-sculpt-light', source: 'tag-sculpt', target: 'tag-light-loop', weight: 0.5 },
    { id: 'edge-light-texture', source: 'tag-light-loop', target: 'tag-texture', weight: 0.42 },
    { id: 'edge-sculpt-texture', source: 'tag-sculpt', target: 'tag-texture', weight: 0.45 },
    { id: 'edge-sound-texture', source: 'tag-sound', target: 'tag-texture', weight: 0.38 },
    { id: 'edge-expression-workshop', source: 'tag-expression', target: 'tag-workshop', weight: 0.33 },
    { id: 'edge-workshop-sound', source: 'tag-workshop', target: 'tag-sound', weight: 0.29 },
    { id: 'edge-archive-golden', source: 'tag-archive', target: 'tag-golden-hour', weight: 0.34 },
    { id: 'edge-portrait-gold', source: 'tag-portrait', target: 'tag-gold', weight: 0.31 },
  ],
}
