#!/bin/bash
set -euo pipefail

# CCFrame 统一管理脚本 (支持源码构建和镜像部署)
# 使用说明：
#   bash ccframe.sh install [--from-image]   # 安装（默认源码构建，--from-image 使用镜像）
#   bash ccframe.sh update [--from-image]    # 更新（默认源码构建，--from-image 使用镜像）
#   bash ccframe.sh start                    # 启动容器
#   bash ccframe.sh stop                     # 停止容器
#   bash ccframe.sh restart                  # 重启容器
#   bash ccframe.sh status                   # 查看容器状态
#   bash ccframe.sh logs [svc]               # 查看日志
#   bash ccframe.sh env                      # 生成或修复 .env
#   bash ccframe.sh health                   # 健康检查
#   bash ccframe.sh uninstall [--purge]      # 卸载
#   bash ccframe.sh switch-mode              # 切换部署模式

# 颜色输出定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

print_banner() {
  echo "==============================================="
  echo "   CCFrame - 私人相册系统"
  echo "   统一部署管理脚本"
  echo "==============================================="
  echo " 功能亮点："
  echo "   - 智能照片管理      - 照片多规格"
  echo "   - 自适应设计        - 访问控制"
  echo "   - PWA 离线支持       - 深色模式"
  echo
}

print_success() { echo -e "${GREEN}[成功] $1${NC}"; }
print_error()   { echo -e "${RED}[错误] $1${NC}"; }
print_warning() { echo -e "${YELLOW}[警告] $1${NC}"; }
print_info()    { echo -e "${BLUE}[提示] $1${NC}"; }
print_step()    { echo -e "${PURPLE}[步骤] $1${NC}"; }

SERVER_IP=""
ACCESS_BASE_URL=""
DEPLOYMENT_METHOD="source"  # source | image
IMAGE_TAG="${IMAGE_TAG:-latest}"  # 支持通过环境变量指定版本
GHCR_IMAGE="ghcr.io/lonelyrower/ccframe:${IMAGE_TAG}"

is_interactive() {
  if [ -t 0 ]; then
    return 0
  fi
  if [ -r /dev/tty ]; then
    return 0
  fi
  return 1
}

detect_server_ip() {
  local ip
  ip=$(hostname -I 2>/dev/null | awk '{print $1}')
  if [ -z "${ip:-}" ]; then
    ip=$(curl -fsSL https://api.ipify.org 2>/dev/null || echo "127.0.0.1")
  fi
  echo "$ip"
}

set_env_value() {
  local key="$1"
  local value="$2"
  local sed_value
  sed_value=${value//\\/\\\\}
  sed_value=${sed_value//&/\\&}
  sed_value=${sed_value//#/\\#}
  if [ -f .env ] && grep -q "^${key}=" .env; then
    sed -i "s#^${key}=.*#${key}=${sed_value}#" .env
  else
    printf '%s=%s\n' "$key" "$value" >> .env
  fi
}

remove_env_key() {
  local key="$1"
  if [ -f .env ]; then
    sed -i "/^${key}=.*/d" .env
  fi
}

get_env_value() {
  local key="$1"
  if [ -f .env ]; then
    grep -m1 "^${key}=" .env | cut -d'=' -f2-
  fi
}

ensure_certbot_webroot() {
  mkdir -p certbot
}

ensure_compose_https_mode() {
  if ! command -v python3 >/dev/null 2>&1; then
    print_warning "python3 未找到，跳过 docker-compose.yml 自动更新，请手动添加 443 端口和证书挂载"
    return
  fi
  python3 <<'PY2'
from pathlib import Path
path = Path("docker-compose.yml")
text = path.read_text()
if '      - "443:443"' not in text:
    text = text.replace('      - "80:80"\n', '      - "80:80"\n      - "443:443"\n', 1)
if '      - ./certbot:/var/www/certbot' not in text:
    text = text.replace('      - ./nginx.conf:/etc/nginx/nginx.conf:ro\n', '      - ./nginx.conf:/etc/nginx/nginx.conf:ro\n      - ./certbot:/var/www/certbot\n', 1)
if '      - /etc/letsencrypt:/etc/letsencrypt:ro' not in text:
    text = text.replace('      - ./nginx.conf:/etc/nginx/nginx.conf:ro\n', '      - ./nginx.conf:/etc/nginx/nginx.conf:ro\n      - /etc/letsencrypt:/etc/letsencrypt:ro\n', 1)
path.write_text(text)
PY2
}

ensure_compose_http_mode() {
  if ! command -v python3 >/dev/null 2>&1; then
    print_warning "python3 未找到，跳过 docker-compose.yml 自动修正，请手动移除 443 端口和证书挂载"
    return
  fi
  python3 <<'PY3'
from pathlib import Path
path = Path("docker-compose.yml")
lines = path.read_text().splitlines()
filtered = [line for line in lines if line.strip() not in {'- "443:443"', '- /etc/letsencrypt:/etc/letsencrypt:ro', '- ./certbot:/var/www/certbot'}]
if filtered and filtered[-1] != '':
    filtered.append('')
path.write_text("\n".join(filtered))
PY3
}

generate_nginx_http_conf() {
  local domain="$1"
  local server_names="_"
  if [ -n "$domain" ]; then
    server_names="$domain _"
  elif [ -n "$SERVER_IP" ]; then
    server_names="$SERVER_IP _"
  fi

  cat > nginx.conf <<EOF
# Generated by ccframe.sh (mode: http)
events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  sendfile on;
  keepalive_timeout 65;

  resolver 127.0.0.11 valid=30s;

  upstream web_backend {
    server web:3000;
  }

  server {
    listen 80 default_server;
    server_name $server_names;

    client_max_body_size 50m;

    location /nginx-health {
      access_log off;
      return 200 "healthy\n";
      add_header Content-Type text/plain;
    }

    location / {
      proxy_pass http://web_backend;
      proxy_http_version 1.1;
      proxy_set_header Host \$host;
      proxy_set_header X-Real-IP \$remote_addr;
      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto \$scheme;
      proxy_set_header Upgrade \$http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_connect_timeout 60s;
      proxy_send_timeout 300s;
      proxy_read_timeout 300s;

      proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
      proxy_next_upstream_tries 3;
      proxy_next_upstream_timeout 30s;
    }
  }
}
EOF
}

generate_nginx_https_conf() {
  local domain="$1"
  local server_names="$domain"
  if [ -z "$domain" ]; then
    print_error "域名为空，无法生成 HTTPS 配置"
    exit 1
  fi

  cat > nginx.conf <<EOF
# Generated by ccframe.sh (mode: https)
events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  sendfile on;
  keepalive_timeout 65;

  resolver 127.0.0.11 valid=30s;

  upstream web_backend {
    server web:3000;
  }

  server {
    listen 80;
    server_name $server_names;

    client_max_body_size 50m;

    location /nginx-health {
      access_log off;
      return 200 "healthy\n";
      add_header Content-Type text/plain;
    }

    location / {
      return 301 https://\$host\$request_uri;
    }
  }

  server {
    listen 443 ssl http2;
    server_name $server_names;

    ssl_certificate /etc/letsencrypt/live/$domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$domain/privkey.pem;
EOF

  if [ -f /etc/letsencrypt/options-ssl-nginx.conf ]; then
    printf '    include /etc/letsencrypt/options-ssl-nginx.conf;\n' >> nginx.conf
  fi
  if [ -f /etc/letsencrypt/ssl-dhparams.pem ]; then
    printf '    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;\n' >> nginx.conf
  fi

  cat <<'EOF' >> nginx.conf
    client_max_body_size 50m;

    location / {
      proxy_pass http://web_backend;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_connect_timeout 60s;
      proxy_send_timeout 300s;
      proxy_read_timeout 300s;

      proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
      proxy_next_upstream_tries 3;
      proxy_next_upstream_timeout 30s;
    }
  }
}
EOF
}

obtain_letsencrypt_certificate() {
  local domain="$1"
  local email="$2"

  if [ -d "/etc/letsencrypt/live/$domain" ]; then
    print_info "检测到现有证书 /etc/letsencrypt/live/$domain"
    return
  fi

  print_step "申请 Let's Encrypt 证书 ($domain)..."
  apt-get update -y >/dev/null 2>&1 || true
  apt-get install -y certbot >/dev/null 2>&1 || true

  systemctl stop nginx 2>/dev/null || service nginx stop 2>/dev/null || true
  docker stop ccframe-nginx >/dev/null 2>&1 || true

  if certbot certonly --standalone --agree-tos --no-eff-email -m "$email" -d "$domain"; then
    print_success "证书申请成功"
  else
    print_error "证书申请失败，请确认域名解析已经指向本服务器"
    exit 1
  fi
}

configure_certbot_cron() {
  local cron_file="/etc/cron.d/ccframe-certbot"
  cat > "$cron_file" <<'EOF'
SHELL=/bin/bash
0 3 * * * root certbot renew --standalone --pre-hook "docker stop ccframe-nginx >/dev/null 2>&1 || true" --post-hook "docker start ccframe-nginx >/dev/null 2>&1 || true" >> /var/log/ccframe-certbot.log 2>&1
EOF
  chmod 644 "$cron_file" >/dev/null 2>&1 || true
  print_success "已写入证书自动续期任务 (/etc/cron.d/ccframe-certbot)"
}

configure_ip_mode() {
  DEPLOYMENT_MODE="ip"
  SERVER_IP=${SERVER_IP:-$(detect_server_ip)}
  ACCESS_BASE_URL="http://$SERVER_IP"
  set_env_value "DEPLOYMENT_MODE" "$DEPLOYMENT_MODE"
  set_env_value "NEXTAUTH_URL" "$ACCESS_BASE_URL"
  set_env_value "FORCE_HTTPS" "false"
  set_env_value "APP_DOMAIN" ""
  set_env_value "SSL_EMAIL" ""
  ensure_compose_http_mode
  generate_nginx_http_conf ""
  print_info "当前使用 IP 部署模式 (HTTP): $ACCESS_BASE_URL"
}

configure_letsencrypt_mode() {
  DEPLOYMENT_MODE="letsencrypt"
  local domain=$(get_env_value APP_DOMAIN)
  local email=$(get_env_value SSL_EMAIL)

  if [ -z "$domain" ]; then
    if is_interactive; then
      read -rp "请输入绑定的域名: " domain
      while [ -z "$domain" ]; do
        print_warning "域名不能为空"
        read -rp "请输入绑定的域名: " domain
      done
    else
      print_error "未配置 APP_DOMAIN，无法在非交互模式下启用 HTTPS"
      exit 1
    fi
  fi

  if [ -z "$email" ]; then
    if is_interactive; then
      read -rp "请输入用于 Let's Encrypt 的邮箱: " email
      while [ -z "$email" ]; do
        print_warning "邮箱不能为空"
        read -rp "请输入用于 Let's Encrypt 的邮箱: " email
      done
    else
      print_error "未配置 SSL_EMAIL，无法在非交互模式下启用 HTTPS"
      exit 1
    fi
  fi

  set_env_value "DEPLOYMENT_MODE" "$DEPLOYMENT_MODE"
  set_env_value "APP_DOMAIN" "$domain"
  set_env_value "SSL_EMAIL" "$email"
  set_env_value "FORCE_HTTPS" "true"

  ACCESS_BASE_URL="https://$domain"
  set_env_value "NEXTAUTH_URL" "$ACCESS_BASE_URL"

  ensure_certbot_webroot
  obtain_letsencrypt_certificate "$domain" "$email"
  ensure_compose_https_mode
  generate_nginx_https_conf "$domain"
  configure_certbot_cron
  print_info "已配置域名 HTTPS 模式: $ACCESS_BASE_URL"
}

configure_cloudflare_mode() {
  DEPLOYMENT_MODE="cloudflare"
  local domain=$(get_env_value APP_DOMAIN)

  if [ -z "$domain" ]; then
    if is_interactive; then
      read -rp "请输入绑定的域名: " domain
      while [ -z "$domain" ]; do
        print_warning "域名不能为空"
        read -rp "请输入绑定的域名: " domain
      done
    else
      print_error "未配置 APP_DOMAIN，无法在非交互模式下启用 Cloudflare 模式"
      exit 1
    fi
  fi

  set_env_value "DEPLOYMENT_MODE" "$DEPLOYMENT_MODE"
  set_env_value "APP_DOMAIN" "$domain"
  set_env_value "SSL_EMAIL" ""
  set_env_value "FORCE_HTTPS" "true"

  ACCESS_BASE_URL="https://$domain"
  set_env_value "NEXTAUTH_URL" "$ACCESS_BASE_URL"

  ensure_compose_http_mode
  generate_nginx_http_conf "$domain"
  print_info "已配置 Cloudflare/CDN 模式，请在代理层开启 HTTPS：$ACCESS_BASE_URL"
}

configure_deployment_target() {
  local current_mode=$(get_env_value DEPLOYMENT_MODE)
  local choice="${current_mode:-}"

  if [ -n "$current_mode" ] && is_interactive; then
    read -rp "检测到现有部署模式 ($current_mode)，是否需要重新配置? [y/N]: " change
    case "${change,,}" in
      y|yes)
        choice=""
        ;;
    esac
  fi

  if [ -z "$choice" ]; then
    if is_interactive; then
      echo "请选择部署模式："
      echo "  1) IP 模式（仅 HTTP，使用服务器 IP 访问）"
      echo "  2) 域名模式（自动申请 Let's Encrypt HTTPS）"
      echo "  3) 域名 + 反向代理模式（HTTPS 由 Cloudflare/CDN 提供）"
      read -rp "请输入选项 [1/2/3] (默认 1): " choice
    else
      choice="1"
    fi
  fi

  choice=${choice:-1}

  case "$choice" in
    1|ip|http)
      configure_ip_mode
      ;;
    2|letsencrypt|https|domain)
      configure_letsencrypt_mode
      ;;
    3|cloudflare|cdn|proxy)
      configure_cloudflare_mode
      ;;
    *)
      print_warning "未知选项 $choice，自动使用 IP 模式"
      configure_ip_mode
      ;;
  esac
}

DOCKER_COMPOSE_CMD=""

check_system() {
  print_step "正在检查系统环境..."

  if [[ "${OSTYPE:-}" != linux* ]]; then
    print_error "此脚本仅支持 Linux 服务器（VPS）"
    exit 1
  fi
  print_success "检测到操作系统：Linux"

  if ! command -v git >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1; then
    print_info "正在安装 git/curl..."
    apt-get update -y >/dev/null 2>&1 || true
    apt-get install -y git curl >/dev/null 2>&1 || true
  fi
  print_success "git/curl 已就绪"

  if ! command -v docker >/dev/null 2>&1; then
    print_info "正在安装 Docker..."
    curl -fsSL https://get.docker.com | sh
  fi
  print_success "Docker 版本：$(docker --version | cut -d' ' -f3)"

  if docker compose version >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD="docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD="docker-compose"
  else
    print_info "正在安装 Docker Compose 插件..."
    apt-get install -y docker-compose-plugin >/dev/null 2>&1 || true
    if docker compose version >/dev/null 2>&1; then
      DOCKER_COMPOSE_CMD="docker compose"
    else
      print_error "无法找到 Docker Compose 命令"
      exit 1
    fi
  fi
  print_success "Compose 命令：$DOCKER_COMPOSE_CMD"
}

clone_project() {
  print_step "正在获取项目代码..."

  PROJECT_DIR="/opt/ccframe"
  REPO_URL="https://github.com/lonelyrower/CCFrame.git"
  BRANCH="main"

  mkdir -p "$PROJECT_DIR"

  if [ -d "$PROJECT_DIR/.git" ]; then
    cd "$PROJECT_DIR" || { print_error "无法进入目录 $PROJECT_DIR"; exit 1; }
    print_info "正在更新已有仓库..."

    if git pull --rebase --autostash; then
      print_success "代码更新成功"
      return
    else
      print_warning "git pull 失败，尝试强制重置..."
      git fetch --all --prune || true
      if git reset --hard "origin/$BRANCH" 2>/dev/null; then
        print_success "已强制重置到最新代码"
        return
      else
        print_warning "更新失败，将重新克隆..."
        cd /
        rm -rf "$PROJECT_DIR"
        mkdir -p "$PROJECT_DIR"
      fi
    fi
  fi

  print_info "正在克隆仓库：$REPO_URL -> $PROJECT_DIR"
  if git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$PROJECT_DIR"; then
    cd "$PROJECT_DIR" || { print_error "无法进入目录 $PROJECT_DIR"; exit 1; }
    print_success "仓库克隆成功：$PROJECT_DIR"
    return
  fi

  print_error "克隆仓库失败：$REPO_URL"
  exit 1
}

prepare_image_compose() {
  print_step "生成镜像部署 docker-compose.yml..."

  cat > docker-compose.yml <<'EOF'
services:
  web:
    image: ghcr.io/lonelyrower/ccframe:${IMAGE_TAG:-latest}
    container_name: ccframe-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    command:
      - sh
      - -c
      - |
        set -e
        echo 'Applying database migrations...'
        for i in $(seq 1 60); do npx prisma migrate deploy && break || (echo 'DB not ready, retry...' && sleep 2); done
        npx prisma generate
        node scripts/create-admin.js || true
        echo 'Starting Next.js server on port 3000...'
        npm start
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health-simple || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    networks:
      - ccframe

  worker:
    image: ghcr.io/lonelyrower/ccframe:${IMAGE_TAG:-latest}
    container_name: ccframe-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      START_WORKERS: 'true'
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    command:
      - sh
      - -c
      - |
        set -e
        echo 'Applying database migrations for worker...'
        for i in $(seq 1 60); do npx prisma migrate deploy && break || (echo 'DB not ready, retry...' && sleep 2); done
        npx prisma generate
        node scripts/start-worker.js
    networks:
      - ccframe

  db:
    image: postgres:15-alpine
    container_name: ccframe-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ccframe}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ccframe}
      POSTGRES_DB: ${POSTGRES_DB:-ccframe}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ccframe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ccframe} -d ${POSTGRES_DB:-ccframe}"]
      interval: 3s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: ccframe-redis
    restart: unless-stopped
    networks:
      - ccframe

  minio:
    image: minio/minio:latest
    container_name: ccframe-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - ccframe

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-ccframe}
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-}"
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    command: >-
      set -e;
      echo "Waiting for MinIO to be ready...";
      until mc alias set local http://minio:9000 "$${MINIO_ROOT_USER}" "$${MINIO_ROOT_PASSWORD}" 2>/dev/null; do
        echo "MinIO not ready, waiting...";
        sleep 2;
      done;
      echo "MinIO is ready!";
      SHOULD_CREATE_USER=0;
      if [ -n "$${S3_ACCESS_KEY_ID}" ] && [ -n "$${S3_SECRET_ACCESS_KEY}" ]; then
        if [ "$${S3_ACCESS_KEY_ID}" != "$${MINIO_ROOT_USER}" ] || [ "$${S3_SECRET_ACCESS_KEY}" != "$${MINIO_ROOT_PASSWORD}" ]; then
          SHOULD_CREATE_USER=1;
        fi;
      fi;
      if [ "$${SHOULD_CREATE_USER}" -eq 1 ]; then
        mc admin user add local "$${S3_ACCESS_KEY_ID}" "$${S3_SECRET_ACCESS_KEY}" || true;
        mc admin policy attach local readwrite --user "$${S3_ACCESS_KEY_ID}" || true;
      fi;
      BUCKET_NAME="$${S3_BUCKET_NAME:-ccframe}";
      mc mb -p "local/$${BUCKET_NAME}" || true;
      mc mb -p local/photo-gallery || true;
      echo 'MinIO buckets ensured';
    networks:
      - ccframe

  nginx:
    image: nginx:1.25-alpine
    container_name: ccframe-nginx
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ccframe
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/nginx-health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pgdata:
  minio:

networks:
  ccframe:
    driver: bridge
EOF

  print_success "已生成镜像部署配置"
}

ensure_compose_integrity() {
  cd /opt/ccframe || return 1
  local f="docker-compose.yml"
  local FORCE="${1:-0}"
  if [ ! -f "$f" ]; then
    print_error "未找到 $f"
    return 1
  fi

  if [ "$FORCE" = "1" ]; then
    print_warning "使用 --fix-compose 强制覆盖 docker-compose.yml 为上游版本"
    curl -fsSL https://raw.githubusercontent.com/lonelyrower/CCFrame/main/docker-compose.yml -o "$f" || true
  fi

  sed -i 's/\r$//' "$f" 2>/dev/null || true
  awk 'NR==1{sub(/^[\xef\xbb\xbf]/,"")} {print}' "$f" > "$f.tmp" 2>/dev/null && mv "$f.tmp" "$f" || true

  if grep -qE '^(<<<<<<<|=======|>>>>>>>)[ ]' "$f"; then
    print_warning "检测到 docker-compose.yml 存在合并冲突，尝试恢复为上游版本"
    curl -fsSL https://raw.githubusercontent.com/lonelyrower/CCFrame/main/docker-compose.yml -o "$f" || true
  fi

  local svc_count
  svc_count=$(grep -n '^services:' "$f" | wc -l | tr -d ' ')
  if [ "$svc_count" -gt 1 ]; then
    local last_line
    last_line=$(grep -n '^services:' "$f" | tail -1 | cut -d: -f1)
    tail -n +"$last_line" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
  fi

  if ! grep -q '/api/health-simple' "$f"; then
    sed -i 's#/api/health"#/api/health-simple"#g' "$f" 2>/dev/null || true
    sed -i 's#/api/health #/api/health-simple #g' "$f" 2>/dev/null || true
  fi

  if ! $DOCKER_COMPOSE_CMD -f "$f" config >/dev/null 2>&1; then
    print_warning "当前 docker-compose.yml 解析失败，回退为上游版本"
    curl -fsSL https://raw.githubusercontent.com/lonelyrower/CCFrame/main/docker-compose.yml -o "$f" || true
  fi

  if $DOCKER_COMPOSE_CMD -f "$f" config >/dev/null 2>&1; then
    print_success "docker-compose.yml 已修复并通过校验"
  else
    print_error "docker-compose.yml 仍无法解析，请手动检查"
  fi
}

ensure_env() {
  print_step "正在检查并生成环境变量..."

  if [ ! -f .env ]; then
    if [ -f .env.docker.example ]; then
      cp .env.docker.example .env
      print_success ".env 已从 .env.docker.example 复制"
    else
      print_warning "未找到 .env.docker.example，将基于默认模板生成 .env"

      local _ts=$(date +%s)
      local NEXTAUTH_SECRET ADMIN_PASSWORD POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB
      local S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY MINIO_ROOT_USER MINIO_ROOT_PASSWORD
      NEXTAUTH_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "change-me-${_ts}")
      ADMIN_PASSWORD=$(openssl rand -base64 12 2>/dev/null || echo "admin-${_ts}")
      POSTGRES_USER=ccframe
      POSTGRES_PASSWORD=$(openssl rand -base64 16 2>/dev/null || echo "db-${_ts}")
      POSTGRES_DB=ccframe
      S3_ACCESS_KEY_ID=$(openssl rand -base64 12 2>/dev/null || echo "s3-${_ts}")
      S3_SECRET_ACCESS_KEY=$(openssl rand -base64 16 2>/dev/null || echo "s3secret-${_ts}")
      MINIO_ROOT_USER=$(openssl rand -base64 12 2>/dev/null || echo "minio-${_ts}")
      MINIO_ROOT_PASSWORD=$(openssl rand -base64 16 2>/dev/null || echo "miniosecret-${_ts}")

      cat > .env <<EOF
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ADMIN_EMAIL=admin@local.dev
ADMIN_PASSWORD=${ADMIN_PASSWORD}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
REDIS_URL=redis://redis:6379
S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
S3_BUCKET_NAME=ccframe
S3_REGION=us-east-1
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
ENABLE_SEMANTIC_SEARCH=true
SEMANTIC_USE_PGVECTOR=off
EMBED_PROVIDER=openai
EMBED_MODEL_NAME=text-embedding-3-small
EMBED_DIM=1536
# 使用 OPENAI_API_KEY 指定 OpenAI API Key
EOF
    fi
  fi

  SERVER_IP=$(detect_server_ip)
  configure_deployment_target

  if [ -n "$ACCESS_BASE_URL" ]; then
    print_success "已将 NEXTAUTH_URL 设置为 $ACCESS_BASE_URL"
  else
    print_success "环境变量检查完成"
  fi
}

show_info() {
  local base_url
  base_url=$(get_env_value NEXTAUTH_URL)
  if [ -z "$base_url" ]; then
    SERVER_IP=${SERVER_IP:-$(detect_server_ip)}
    base_url="http://$SERVER_IP"
  fi
  local trimmed="${base_url%/}"
  local admin_url="${trimmed}/admin/login"
  local server_ip=${SERVER_IP:-$(detect_server_ip)}
  local deployment_mode=$(get_env_value DEPLOYMENT_MODE)
  local app_domain=$(get_env_value APP_DOMAIN)

  local ADMIN_PASSWORD="请在 .env 中确认 ADMIN_PASSWORD"
  if [ -f .env ] && grep -q '^ADMIN_PASSWORD=' .env; then
    ADMIN_PASSWORD=$(grep '^ADMIN_PASSWORD=' .env | cut -d'=' -f2 | tr -d '"')
  fi

  echo ""
  print_info "服务访问信息"
  echo ""
  echo "访问地址:"
  echo "  前台站点: ${trimmed}/"
  echo "  管理后台: ${admin_url}"
  if [ -n "$app_domain" ]; then
    echo "  绑定域名: $app_domain"
  fi
  echo "  服务器 IP: $server_ip"
  echo ""
  echo "默认管理员:"
  echo "  邮箱: admin@local.dev"
  echo "  密码: $ADMIN_PASSWORD"
  echo ""
  echo "部署模式: ${deployment_mode:-ip}"
  echo "  部署方式: ${DEPLOYMENT_METHOD}"
  echo "  MinIO 控制台: http://$server_ip:9001"
  echo ""
  echo "常用命令:"
  echo "  停止: bash ccframe.sh stop"
  echo "  重启: bash ccframe.sh restart"
  echo "  查看日志: bash ccframe.sh logs"
  echo "  切换模式: bash ccframe.sh switch-mode"
  echo ""
}

cmd_install() {
  check_system

  local USE_IMAGE=0
  for arg in "$@"; do
    case "$arg" in
      --from-image) USE_IMAGE=1 ;;
    esac
  done

  if [ "$USE_IMAGE" -eq 1 ]; then
    DEPLOYMENT_METHOD="image"
    print_info "使用镜像部署模式"

    PROJECT_DIR="/opt/ccframe"
    mkdir -p "$PROJECT_DIR"
    cd "$PROJECT_DIR" || { print_error "无法进入目录 $PROJECT_DIR"; exit 1; }

    prepare_image_compose
    ensure_env

    print_step "拉取最新镜像: $GHCR_IMAGE"
    if docker pull "$GHCR_IMAGE"; then
      print_success "镜像拉取成功"
    else
      print_error "镜像拉取失败"
      print_info "可能的原因："
      print_info "  1. 网络问题 - 请检查网络连接"
      print_info "  2. 镜像不存在 - 请确认镜像地址: $GHCR_IMAGE"
      print_info "  3. 认证问题 - 如果是私有镜像，需要先登录: docker login ghcr.io"
      exit 1
    fi
  else
    DEPLOYMENT_METHOD="source"
    print_info "使用源码构建模式"

    clone_project
    ensure_env

    local FORCE_FIX_COMPOSE=0
    for arg in "$@"; do
      case "$arg" in
        --fix-compose) FORCE_FIX_COMPOSE=1 ;;
      esac
    done

    ensure_compose_integrity "$FORCE_FIX_COMPOSE"
  fi

  print_step "正在清理旧容器与缓存..."
  $DOCKER_COMPOSE_CMD down --remove-orphans 2>/dev/null || true
  docker system prune -f --volumes >/dev/null 2>&1 || true
  docker network prune -f >/dev/null 2>&1 || true
  docker volume prune -f >/dev/null 2>&1 || true

  systemctl stop nginx 2>/dev/null || service nginx stop 2>/dev/null || true
  print_success "清理完成"

  print_step "正在启动容器..."
  if [ "$USE_IMAGE" -eq 1 ]; then
    $DOCKER_COMPOSE_CMD up -d
  else
    $DOCKER_COMPOSE_CMD up -d --build --force-recreate
  fi

  show_info
}

cmd_update() {
  check_system

  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install 操作"; exit 1; }

  local USE_IMAGE=0
  for arg in "$@"; do
    case "$arg" in
      --from-image) USE_IMAGE=1 ;;
    esac
  done

  if [ "$USE_IMAGE" -eq 1 ]; then
    DEPLOYMENT_METHOD="image"
    print_info "使用镜像部署模式更新"

    prepare_image_compose
    ensure_env

    print_step "拉取最新镜像: $GHCR_IMAGE"
    if docker pull "$GHCR_IMAGE"; then
      print_success "镜像拉取成功"
    else
      print_error "镜像拉取失败"
      print_info "可能的原因："
      print_info "  1. 网络问题 - 请检查网络连接"
      print_info "  2. 镜像不存在 - 请确认镜像地址: $GHCR_IMAGE"
      print_info "  3. 认证问题 - 如果是私有镜像，需要先登录: docker login ghcr.io"
      exit 1
    fi

    print_step "正在更新容器..."
    $DOCKER_COMPOSE_CMD up -d
  else
    DEPLOYMENT_METHOD="source"
    print_info "使用源码构建模式更新"

    clone_project
    ensure_env

    local FORCE_FIX_COMPOSE=0
    for arg in "$@"; do
      case "$arg" in
        --fix-compose) FORCE_FIX_COMPOSE=1 ;;
      esac
    done

    ensure_compose_integrity "$FORCE_FIX_COMPOSE"

    print_step "正在清理构建缓存..."
    docker builder prune -f >/dev/null 2>&1 || true

    print_step "正在重新构建并启动..."
    $DOCKER_COMPOSE_CMD up -d --build --force-recreate
  fi

  show_info
}

cmd_switch_mode() {
  check_system
  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install 操作"; exit 1; }

  echo "请选择新的部署方式："
  echo "  1) 镜像部署（快速，资源占用少）"
  echo "  2) 源码构建（可自定义修改）"
  read -rp "请输入选项 [1/2]: " choice

  case "$choice" in
    1)
      print_info "切换到镜像部署模式..."
      cmd_update --from-image
      ;;
    2)
      print_info "切换到源码构建模式..."
      cmd_update
      ;;
    *)
      print_error "无效选项"
      exit 1
      ;;
  esac
}

cmd_start() {
  check_system
  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install 操作"; exit 1; }
  $DOCKER_COMPOSE_CMD up -d
  show_info
}

cmd_stop() {
  check_system
  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install 操作"; exit 1; }
  $DOCKER_COMPOSE_CMD down
  print_success "所有容器已停止"
}

cmd_restart() {
  check_system
  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install 操作"; exit 1; }
  $DOCKER_COMPOSE_CMD restart
  show_info
}

cmd_status() {
  check_system
  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install 操作"; exit 1; }
  $DOCKER_COMPOSE_CMD ps
}

cmd_logs() {
  check_system
  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install 操作"; exit 1; }
  svc=${1:-}
  if [ -n "$svc" ]; then
    $DOCKER_COMPOSE_CMD logs -f --tail=200 "$svc"
  else
    $DOCKER_COMPOSE_CMD logs -f --tail=200
  fi
}

cmd_env() {
  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install 操作"; exit 1; }
  ensure_env
}

cmd_health() {
  cd /opt/ccframe || { print_error "未找到项目目录，请先执行 install"; exit 1; }
  local base_url=$(get_env_value NEXTAUTH_URL)
  if [ -z "$base_url" ]; then
    base_url="http://$(detect_server_ip)"
  fi
  base_url=${base_url%/}
  curl -fsSL "$base_url/api/health-simple" || echo '{"ok":false}'
}

cmd_uninstall() {
  check_system
  local PURGE=0 YES=0
  while [ $# -gt 0 ]; do
    case "$1" in
      --purge) PURGE=1 ;;
      -y|--yes) YES=1 ;;
    esac
    shift
  done

  print_warning "即将卸载 CCFrame，将停止并移除容器${PURGE:+，并删除数据卷和应用目录}。"
  if [ "$YES" -ne 1 ]; then
    read -rp "请输入 'uninstall' 以确认：" confirm || exit 1
    [ "$confirm" = "uninstall" ] || { print_error "已取消"; exit 1; }
  fi

  if [ -d /opt/ccframe ]; then
    cd /opt/ccframe || true
    if [ -f docker-compose.yml ] || [ -f docker-compose.yaml ] || [ -f compose.yml ] || [ -f compose.yaml ]; then
      if [ "$PURGE" -eq 1 ]; then
        print_step "正在停止并移除容器，同时删除数据卷..."
        $DOCKER_COMPOSE_CMD down -v || true
      else
        print_step "正在停止并移除容器..."
        $DOCKER_COMPOSE_CMD down || true
      fi
    fi
  fi

  print_step "清理残留容器..."
  for c in ccframe-web ccframe-worker ccframe-nginx ccframe-minio ccframe-postgres ccframe-redis; do
    docker rm -f "$c" >/dev/null 2>&1 || true
  done
  docker network rm ccframe >/dev/null 2>&1 || true

  if [ "$PURGE" -eq 1 ]; then
    print_step "删除数据卷..."
    docker volume rm pgdata >/dev/null 2>&1 || true
    docker volume rm minio >/dev/null 2>&1 || true
  fi

  print_step "清理systemd服务..."
  for service in ccframe-web ccframe-worker; do
    if systemctl is-active --quiet "$service" 2>/dev/null; then
      systemctl stop "$service" || true
    fi
    if systemctl is-enabled --quiet "$service" 2>/dev/null; then
      systemctl disable "$service" || true
    fi
    if [ -f "/etc/systemd/system/$service.service" ]; then
      rm -f "/etc/systemd/system/$service.service" || true
    fi
  done
  systemctl daemon-reload 2>/dev/null || true

  if [ "$PURGE" -eq 1 ] && [ -d /opt/ccframe ]; then
    print_step "删除应用目录 /opt/ccframe..."
    rm -rf /opt/ccframe || true
  elif [ -d /opt/ccframe ]; then
    print_info "保留应用目录 /opt/ccframe（使用 --purge 参数可完全删除）"
  fi

  if [ "$PURGE" -eq 1 ]; then
    print_step "清理相关Docker镜像..."
    docker images --format "table {{.Repository}}:{{.Tag}}" | grep -E "(ccframe|lonelyrower/ccframe)" | awk '{print $1}' | xargs -r docker rmi 2>/dev/null || true
  fi

  print_success "卸载完成${PURGE:+（已完全清理）}"
  if [ "$PURGE" -ne 1 ]; then
    print_info "提示：使用 'bash ccframe.sh uninstall --purge' 可完全删除所有文件和数据"
  fi
}

interactive_menu() {
  if [ -r /dev/tty ]; then
    exec </dev/tty
  fi
  echo ""
  print_info "请选择要执行的操作："
  echo "  1) 初始化安装（源码构建）"
  echo "  2) 初始化安装（镜像部署）"
  echo "  3) 更新（源码构建）"
  echo "  4) 更新（镜像部署）"
  echo "  5) 切换部署模式"
  echo "  6) 启动"
  echo "  7) 重启"
  echo "  8) 停止"
  echo "  9) 查看状态"
  echo " 10) 查看日志"
  echo " 11) 生成或修复 .env"
  echo " 12) 健康检查"
  echo " 13) 卸载"
  echo "  0) 退出"
  read -rp "请输入数字：" choice || exit 0
  case "$choice" in
    1) cmd_install; exit 0 ;;
    2) cmd_install --from-image; exit 0 ;;
    3) cmd_update; exit 0 ;;
    4) cmd_update --from-image; exit 0 ;;
    5) cmd_switch_mode; exit 0 ;;
    6) cmd_start; exit 0 ;;
    7) cmd_restart; exit 0 ;;
    8) cmd_stop; exit 0 ;;
    9) cmd_status; exit 0 ;;
    10) read -rp "服务名称（可选）：" svc; cmd_logs "$svc"; exit 0 ;;
    11) cmd_env; exit 0 ;;
    12) cmd_health; exit 0 ;;
    13) read -rp "需要完全删除吗？输入 'yes' 删除所有数据和文件，输入其他保留应用目录：" a; if [ "$a" = "yes" ]; then cmd_uninstall --purge; else cmd_uninstall; fi; exit 0 ;;
    0) exit 0 ;;
    *) echo "请输入有效的数字"; exit 1 ;;
  esac
}

main() {
  print_banner
  case "${1:-}" in
    install)        shift; cmd_install "$@"; exit 0 ;;
    update)         shift; cmd_update "$@"; exit 0 ;;
    switch-mode)    shift; cmd_switch_mode "$@"; exit 0 ;;
    start)          shift; cmd_start "$@"; exit 0 ;;
    stop)           shift; cmd_stop "$@"; exit 0 ;;
    restart)        shift; cmd_restart "$@"; exit 0 ;;
    status)         shift; cmd_status "$@"; exit 0 ;;
    logs)           shift; cmd_logs "$@"; exit 0 ;;
    env)            shift; cmd_env "$@"; exit 0 ;;
    health)         shift; cmd_health "$@"; exit 0 ;;
    uninstall)      shift; cmd_uninstall "$@"; exit 0 ;;
    *)
      if [ -t 0 ] || [ -r /dev/tty ]; then
        interactive_menu
      else
        echo "用法：bash ccframe.sh [install|update|switch-mode|start|stop|restart|status|logs|env|health|uninstall]"
        echo "示例："
        echo "  bash ccframe.sh install              # 源码构建安装"
        echo "  bash ccframe.sh install --from-image # 镜像部署安装"
        echo "  bash ccframe.sh update --from-image  # 镜像更新"
        echo "  bash ccframe.sh switch-mode          # 切换部署模式"
        exit 0
      fi
      ;;
  esac
}

trap 'print_error "操作已中断"; exit 1' INT TERM

main "$@"